version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: sdgadmin
      POSTGRES_PASSWORD: sdgpassword
      POSTGRES_DB: sdgdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sdgadmin -d sdgdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: